import { GiftTemplate } from "./types";

export const giftTemplates: GiftTemplate[] = [
  {
    id: "flowers",
    emoji: "💐",
    title: "Flowers Money",
    copy: "Keep the blooms coming without the rush.",
    suggestedAmounts: [2000, 5000, 10000],
    customAllowed: true,
  },
  {
    id: "chocolate",
    emoji: "🍫",
    title: "Chocolate Date",
    copy: "Fuel a sweet night with a simple present.",
    suggestedAmounts: [3000, 7000, 12000],
    customAllowed: true,
  },
  {
    id: "dinner",
    emoji: "🍽️",
    title: "Dinner for Two",
    copy: "Help make reservations feel easy.",
    suggestedAmounts: [5000, 12000, 20000],
    customAllowed: true,
  },
  {
    id: "movie",
    emoji: "🎟️",
    title: "Movie Night",
    copy: "Tickets, popcorn, and a little extra.",
    suggestedAmounts: [2500, 6000, 10000],
    customAllowed: true,
  },
  {
    id: "cake",
    emoji: "🧁",
    title: "Cake & Treats",
    copy: "Make dessert the main event.",
    suggestedAmounts: [1500, 4000, 8000],
    customAllowed: true,
  },
  {
    id: "surprise",
    emoji: "🎁",
    title: "Surprise Me",
    copy: "Let them decide how to celebrate.",
    suggestedAmounts: [2000, 5000, 15000],
    customAllowed: true,
  },
  {
    id: "night-in",
    emoji: "🕯️",
    title: "Romantic Night In",
    copy: "Set the mood with a cozy night.",
    suggestedAmounts: [3000, 8000, 15000],
    customAllowed: true,
  },
  {
    id: "shopping",
    emoji: "🛍️",
    title: "Shopping Spree",
    copy: "A little extra for something special.",
    suggestedAmounts: [5000, 15000, 30000],
    customAllowed: true,
  },
  {
    id: "photoshoot",
    emoji: "📸",
    title: "Photoshoot Fund",
    copy: "Capture the memories in style.",
    suggestedAmounts: [4000, 10000, 20000],
    customAllowed: true,
  },
  {
    id: "transport",
    emoji: "🚗",
    title: "Transport to See You",
    copy: "Close the distance with a ride.",
    suggestedAmounts: [2000, 6000, 12000],
    customAllowed: true,
  },
];
